spring: 
 application: 
  name: weshopify-api-gateway
 #main: 
  #allow-bean-definition-overriding: true  
 redis:
    host: 13.214.221.98
    port: 6379
    
 cloud: 
  gateway:
   
   discovery: 
     locator: 
       enabled: true
       lower-case-service-id: false
 
   routes: 
    - id: WESHOPIFY-BRANDS-SERVICE
      uri: lb://WESHOPIFY-BRANDS-SERVICE
      predicates: 
       - Path= /api/gateway/brands/**
      filters: 
       - RewritePath=/api/gateway/brands/(?<segment>.*),/${segment}
    - id: WESHOPIFY-CATEGORIES-SERVICE
      uri: lb://WESHOPIFY-CATEGORIES-SERVICE
      predicates: 
       - Path= /api/gateway/cats/**
      
      filters:
       - RewritePath=/api/gateway/cats/(?<segment>.*),/${segment}
       
    - id: WESHOPIFY-AUTHN-SERVICE
      uri: lb://WESHOPIFY-AUTHN-SERVICE
      predicates: 
       - Path= /api/security/**
      
      filters:
       - RewritePath=/api/security/(?<segment>.*),/${segment}
server: 
 port: 5005

eureka: 
 instance: 
    preferIpAddress: true
    

 
 
  
   
